const GET_INFO = "GET_INFO";
const GET_URL = "GET_URL";
const START_LOADING = "START_LOADING";
const REMOVE_ITEM = "REMOVE_ITEM";
const RESET_INPUT = "RESET_INPUT";
const ERROR = "ERROR";
const URL_ARRAY_SEND = "URL_ARRAY_SEND";

export {
    GET_INFO,
    GET_URL,
    START_LOADING,
    REMOVE_ITEM,
    RESET_INPUT,
    ERROR,
    URL_ARRAY_SEND
}